package com.whoisyuan.itto;

import java.util.ArrayList;

public class ITTOList {
    
    public static ArrayList<DATA.ITTO> ioList = new ArrayList<DATA.ITTO>() {
        {
            add(DATA.ITTO.ENTERPRISE_ENVIRONMENTAL_FACTORS);                // 事业环境因素
            add(DATA.ITTO.ORGANIZATIONAL_PROCESS_ASSETS);                   // 组织过程资产
            add(DATA.ITTO.PROJECT_MANAGEMENT_PLAN);                         // 项目管理计划
            add(DATA.ITTO.SCOPE_MANAGEMENT_PLAN);                           // 范围管理计划
            add(DATA.ITTO.REQUIREMENTS_MANAGEMENT_PLAN);                    // 需求管理计划
            add(DATA.ITTO.SCHEDULE_MANAGEMENT_PLAN);                        // 进度管理计划
            add(DATA.ITTO.COST_MANAGEMENT_PLAN);                            // 成本管理计划
            add(DATA.ITTO.QUALITY_MANAGEMENT_PLAN);                         // 质量管理计划
            add(DATA.ITTO.PROCESS_IMPROVEMENT_PLAN);                        // 过程改进计划
            add(DATA.ITTO.HUMAN_RESOURCE_MANAGEMENT_PLAN);                  // 人力资源管理计划
            add(DATA.ITTO.COMMUNICATIONS_MANAGEMENT_PLAN);                  // 沟通管理计划
            add(DATA.ITTO.RISK_MANAGEMENT_PLAN);                            // 风险管理计划
            add(DATA.ITTO.PROCUREMENT_MANAGEMENT_PLAN);                     // 采购管理计划
            add(DATA.ITTO.STAKEHOLDER_MANAGEMENT_PLAN);                     // 干系人管理计划
            add(DATA.ITTO.SCOPE_BASELINE);                                  // 范围基准
            add(DATA.ITTO.PROJECT_SCOPE_STATEMENT);                         // 项目范围说明书
            add(DATA.ITTO.RISK_REGISTER);                                   // 风险登记册
            add(DATA.ITTO.WORK_PERFORMANCE_DATA);                           // 工作绩效数据
            add(DATA.ITTO.PROJECT_CHARTER);                                 // 项目章程
            add(DATA.ITTO.STAKEHOLDER_REGISTER);                            // 干系人登记册
            add(DATA.ITTO.REQUIREMENT_DOCUMENTATION);                       // 需求文件
            add(DATA.ITTO.PROCUREMENT_DOCUMENTS);                           // 采购文件
            add(DATA.ITTO.PROJECT_DOCUMENTS);                               // 项目文件
            add(DATA.ITTO.RESOURCE_CALENDAR);                               // 资源日历
            add(DATA.ITTO.WORK_PERFORMANCE_REPORTS);                        // 工作绩效报告
            add(DATA.ITTO.ACTIVITY_LIST);                                   // 活动清单
            add(DATA.ITTO.ACTIVITY_ATTRIBUTES);                             // 活动属性
            add(DATA.ITTO.ACTIVITY_RESOURCE_REQUIREMENTS);                  // 活动资源需求
            add(DATA.ITTO.PROJECT_SCHEDULE);                                // 项目进度计划
            add(DATA.ITTO.ACTIVITY_COST_ESTIMATES);                         // 活动成本估算
            add(DATA.ITTO.AGREEMENTS);                                      // 协议
            add(DATA.ITTO.PROJECT_STAFF_ASSIGNMENTS);                       // 项目人员分派
            add(DATA.ITTO.ISSUE_LOG);                                       // 问题日志
            add(DATA.ITTO.APPROVED_CHANGE_REQUESTS);                        // 批准的变更请求
            add(DATA.ITTO.REQUIREMENTS_TRACEABILITY_MATRIX);                // 需求跟踪矩阵
            add(DATA.ITTO.RESOURCE_BREAKDOWN_STRUCTURE);                    // 资源分解结构
            add(DATA.ITTO.ACTIVITY_DURATION_ESTIMATES);                     // 活动持续时间估算
            add(DATA.ITTO.QUALITY_METRICS);                                 // 质量测量指标
            add(DATA.ITTO.PROJECT_STATEMENT_OF_WORK);                       // 项目工作说明书
            add(DATA.ITTO.BUSINESS_CASE);                                   // 商业论证
            add(DATA.ITTO.PROJECT_SCHEDULE_NETWORK_DIAGRAM);                // 项目进度网络图
            add(DATA.ITTO.MILESTONE_LIST);                                  // 里程碑清单
            add(DATA.ITTO.PROJECT_CALENDAR);                                // 项目日历
            add(DATA.ITTO.SCHEDULE_DATA);                                   // 进度数据
            add(DATA.ITTO.SCHEDULE_FORECASTS);                              // 进度预测
            add(DATA.ITTO.BASIS_OF_ESTIMATES);                              // 估算依据
            add(DATA.ITTO.COST_FORECASTS);                                  // 成本预测
            add(DATA.ITTO.PROJECT_FUNDING_REQUIREMENTS);                    // 项目资金需求
            add(DATA.ITTO.TEAM_PERFORMANCED_ASSESSMENTS);                   // 团队绩效评价
            add(DATA.ITTO.PROJECT_COMMUNICATIONS);                          // 项目沟通
            add(DATA.ITTO.QUALITY_CHECKLISTS);                              // 质量核对单
            add(DATA.ITTO.QUALITY_CONTROL_MEASUREMENTS);                    // 质量控制测量结果
            add(DATA.ITTO.DELIVERABLES);                                    // 可交付成果
            add(DATA.ITTO.VERIFIED_DELIVERABLES);                           // 核实的可交付成果
            add(DATA.ITTO.ACCEPTED_DELIVERABLES);                           // 验收的可交付成果
            add(DATA.ITTO.WORK_PERFORMANCE_INFORMATION);                    // 工作绩效信息
            add(DATA.ITTO.CHANGE_LOG);                                      // 变更日志
            add(DATA.ITTO.CHANGE_REQUESTS);                                 // 变更请求
            add(DATA.ITTO.VALIDATED_CHANGES);                               // 确认的变更
            add(DATA.ITTO.MAKE_OR_BUY_DECISIONS);                           // 自制或外购决策
            add(DATA.ITTO.PROCUREMENT_STATEMENT_OF_WORK);                   // 采购工作说明书
            add(DATA.ITTO.SELLER_PROPOSALS);                                // 卖方建议书
            add(DATA.ITTO.SOURCE_SELECTION_CRITERIA);                       // 供方选择标准
            add(DATA.ITTO.PROJECT_MANAGEMENT_PLAN_UPDATES);                 // 项目管理计划更新
            add(DATA.ITTO.PROJECT_DOCUMENTS_UPDATES);                       // 项目文件更新
            add(DATA.ITTO.ORGANIZATIONAL_PROCESS_ASSETS_UPDATES);           // 组织过程资产更新
            add(DATA.ITTO.COST_BASELINE);                                   // 成本基准
            add(DATA.ITTO.SCHEDULE_BASELINE);                               // 进度基准
            add(DATA.ITTO.SELECTED_SELLERS);                                // 选定的卖方
            add(DATA.ITTO.ENTERPRISE_ENVIRONMENTAL_FACTORS_UPDATES);        // 事业环境因素更新
            add(DATA.ITTO.CLOSED_PROCUREMENTS);                             // 结束的采购
            add(DATA.ITTO.FINAL_PRODUCT_SERVICE_OR_RESULT_TRANSITION);      // 最终产品、服务或成果移交
            add(DATA.ITTO.OUTPUTS_FROM_OTHER_PROCESSES);                    // 其他过程的输出
        }
    };

    public static ArrayList<DATA.ITTO> ttList = new ArrayList<DATA.ITTO>() {
        {
            add(DATA.ITTO.EXPERT_JUDGEMENT);                                // 专家判断
            add(DATA.ITTO.MEETINGS);                                        // 会议
            add(DATA.ITTO.ANALYTICAL_TECHNIQUES);                           // 分析技术
            add(DATA.ITTO.RESERVE_ANALYSIS);                                // 储备分析
            add(DATA.ITTO.GROUP_DECISION_MAKING_TECHNIQUES);                // 群体决策技术
            add(DATA.ITTO.PROJECT_MANAGEMENT_SOFTWARE);                     // 项目管理软件
            add(DATA.ITTO.COMMUNICATION_METHODS);                           // 沟通方法
            add(DATA.ITTO.INFORMATION_MANAGEMENT_SYSTEMS);                  // 信息管理系统
            add(DATA.ITTO.INTERPERSONAL_SKILLS);                            // 人际关系技能
            add(DATA.ITTO.LEADS_AND_LAGS);                                  // 提前量与滞后量
            add(DATA.ITTO.ANALOGOUS_ESTIMATING);                            // 类比估算
            add(DATA.ITTO.BENCHMARKING);                                    // 标杆对照
            add(DATA.ITTO.BOTTOM_UP_ESTIMATING);                            // 自下而上估算
            add(DATA.ITTO.COMMUNICATION_MODELS);                            // 沟通模型
            add(DATA.ITTO.COMMUNICATION_TECHNOLOGY);                        // 沟通技术
            add(DATA.ITTO.COST_OF_QUALITY);                                 // 质量成本
            add(DATA.ITTO.DECOMPOSITION);                                   // 分解
            add(DATA.ITTO.FACILIATED_WORKSHOPS);                            // 引导式研讨会
            add(DATA.ITTO.FACILITATION_TECHNIQUES);                         // 引导技术
            add(DATA.ITTO.INSPECTION);                                      // 检查
            add(DATA.ITTO.MODELING_TECHNIQUES);                             // 建模技术
            add(DATA.ITTO.PARAMETRIC_ESTIMATING);                           // 参数估算
            add(DATA.ITTO.PERFORMANCE_REPORTING);                           // 报告绩效
            add(DATA.ITTO.PERFORMANCE_REVIEWS);                             // 绩效审查
            add(DATA.ITTO.PROCUREMENT_NEGOTIATIONS);                        // 采购谈判
            add(DATA.ITTO.PROJECT_MANAGEMENT_INFORMATION_SYSTEM);           // 项目管理信息系统
            add(DATA.ITTO.RECORDS_MANAGEMENT_SYSTEM);                       // 记录管理系统
            add(DATA.ITTO.RESOURCE_OPTIMIZATION_TECHNIQUES);                // 资源优化技术
            add(DATA.ITTO.SCHEDULE_COMPRESSING);                            // 进度压缩
            add(DATA.ITTO.SCHEDULING_TOOL);                                 // 进度计划编制工具
            add(DATA.ITTO.SEVEN_BASIC_QUALITY_TOOLS);                       // 七种基本质量工具
            add(DATA.ITTO.STATISTICAL_SAMPLING);                            // 统计抽样
            add(DATA.ITTO.THREE_POINT_ESTIMATING);                          // 三点估算
            add(DATA.ITTO.STAKEHOLDER_ANALYSIS);                            // 干系人分析
            add(DATA.ITTO.CONTEXT_DIAGRAMS);                                // 系统交互图
            add(DATA.ITTO.DOCUMENT_ANALYSIS);                               // 文件分析
            add(DATA.ITTO.FOCUS_GROUPS);                                    // 焦点小组
            add(DATA.ITTO.GROUP_CREATIVITY_TECHNIQUES);                     // 群体创新技术
            add(DATA.ITTO.INTERVIEWS);                                      // 访谈
            add(DATA.ITTO.OBSERVATIONS);                                    // 观察
            add(DATA.ITTO.PROTOTYPES);                                      // 原型法
            add(DATA.ITTO.QUESTIONNAIRES_AND_SURVEYS);                      // 问卷调查
            add(DATA.ITTO.ALTERNATIVES_GENERATION);                         // 备选方案生成
            add(DATA.ITTO.PRODUCT_ANALYSIS);                                // 产品分析
            add(DATA.ITTO.ROLLING_WAVE_PLANNING);                           // 滚动式规划
            add(DATA.ITTO.DEPENDENCY_DETERMINATION);                        // 确定依赖关系
            add(DATA.ITTO.PRECEDENCE_DIAGRAMMING_METHOD);                   // 紧前关系绘图法
            add(DATA.ITTO.ALTERNATIVE_ANALYSIS);                            // 备选方案分析
            add(DATA.ITTO.PUBLISHED_ESTIMATING_DATA);                       // 发布的估算数据
            add(DATA.ITTO.CRITICAL_PATH_METHOD);                            // 关键链法
            add(DATA.ITTO.CRITICAL_CHAIN_METHOD);                           // 关键路径法
            add(DATA.ITTO.SCHEDULE_NETWORK_ANALYSIS);                       // 进度网络分析
            add(DATA.ITTO.VENDOR_BID_ANALYSIS);                             // 卖方投标分析
            add(DATA.ITTO.COST_AGGREGATION);                                // 成本汇总
            add(DATA.ITTO.FUNDING_LIMIT_RECONCILIATION);                    // 资金限制平衡
            add(DATA.ITTO.HISTORICAL_RELATIONSHIPS);                        // 历史关系
            add(DATA.ITTO.ADDITIONAL_QUALITY_PLANNING);                     // 其他质量管理工具
            add(DATA.ITTO.COST_BENEFIT_ANALYSIS);                           // 成本效益分析
            add(DATA.ITTO.DESIGN_OF_EXPERIMENTS);                           // 实验设计
            add(DATA.ITTO.NETWORKING);                                      // 人际交往
            add(DATA.ITTO.ORGANIZATION_CHARTS_AND_POSITION_DESCRIPTIONS);   // 组织图和职位描述
            add(DATA.ITTO.ORGANIZATION_THEORY);                             // 组织理论
            add(DATA.ITTO.COMMUNICATION_REQUIREMENTS_ANALYSIS);             // 沟通需求分析
            add(DATA.ITTO.ASSUMPTIONS_ANALYSIS);                            // 假设分析
            add(DATA.ITTO.CHECKLIST_ANALYSIS);                              // 核对单分析
            add(DATA.ITTO.DIAGRAMMING_TECHNIQUES);                          // 图解技术
            add(DATA.ITTO.DOCUMENTATION_REVIEWS);                           // 文档审查
            add(DATA.ITTO.INFORMATION_GATHERING_TECHNIQUES);                // 信息收集技术
            add(DATA.ITTO.SWOT_ANALYSIS);                                   // SWOT分析
            add(DATA.ITTO.PROBABILITY_AND_IMPACT_MATRIX);                   // 概率和影响矩阵
            add(DATA.ITTO.RISK_CATEGORIZATION);                             // 风险分类
            add(DATA.ITTO.RISK_DATA_QUALITY_ASSESSMENT);                    // 风险数据质量评估
            add(DATA.ITTO.RISK_PROBABILITY_AND_IMPACT_ASSESSMENT);          // 风险概率和影响评估
            add(DATA.ITTO.RISK_URGENCY_ASSESSMENT);                         // 风险紧迫性评估
            add(DATA.ITTO.DATA_GATHERING_AND_REPRESENTATION_TECHNIQUES);    // 数据收集和展示技术
            add(DATA.ITTO.QUANTITATIVE_RISK_ANALYSIS_AND_MODELING_TECHNIQUES); // 定量风险分析与建模技术
            add(DATA.ITTO.CONTINGENT_RESPONSE_STRATEGIES);                  // 应急应对策略
            add(DATA.ITTO.STRATEGIES_FOR_NEGATIVE_RISKS_OR_THREATS);        // 消极风险或威胁的应对策略
            add(DATA.ITTO.STRATEGIES_FOR_POSITIVE_RISKS_OR_OPPORTUNITIES);  // 积极风险或机会的应对策略
            add(DATA.ITTO.MAKE_OR_BUY_ANALYSIS);                            // 自制或外购分析
            add(DATA.ITTO.MARKET_RESEARCH);                                 // 市场调研
            add(DATA.ITTO.PROCESS_ANALYSIS);                                // 过程分析
            add(DATA.ITTO.QUALITY_AUDITS);                                  // 质量审计
            add(DATA.ITTO.QUALITY_MANAGEMENT_AND_CONTROL_TOOLS);            // 质量管理和控制工具
            add(DATA.ITTO.ACQUISITION);                                     // 招募
            add(DATA.ITTO.MULTI_CRITERIA_DECISION_ANALYSIS);                // 多标准决策分析
            add(DATA.ITTO.NEGOTIATION);                                     // 谈判
            add(DATA.ITTO.PRE_ASSIGNMENT);                                  // 预分派
            add(DATA.ITTO.VIRTUAL_TEAMS);                                   // 虚拟团队
            add(DATA.ITTO.COLOCATION);                                      // 集中办公
            add(DATA.ITTO.GROUND_RULES);                                    // 基本规则
            add(DATA.ITTO.PERSONNEL_ASSESSMENT_TOOLS);                      // 人事测评工具
            add(DATA.ITTO.RECOGNITION_AND_REWARDS);                         // 认可与奖励
            add(DATA.ITTO.TEAM_BUILDING_ACTIVITIES);                        // 团队建设活动
            add(DATA.ITTO.TRAINING);                                        // 培训
            add(DATA.ITTO.CONFLICT_MANAGEMENT);                             // 冲突管理
            add(DATA.ITTO.OBSERVATION_AND_CONVERSATION);                    // 观察和交谈
            add(DATA.ITTO.PROJECT_PERFORMANCE_APPRAISALS);                  // 项目绩效评估
            add(DATA.ITTO.ADVERTISING);                                     // 广告
            add(DATA.ITTO.BIDDER_CONFERENCE);                               // 投标人会议
            add(DATA.ITTO.INDEPENDENT_ESTIMATES);                           // 独立估算
            add(DATA.ITTO.PROPOSAL_EVALUATION_TECHNIQUES);                  // 建议书评审技术
            add(DATA.ITTO.MANAGEMENT_SKILLS);                               // 管理技能
            add(DATA.ITTO.VARIANCE_ANALYSIS);                               // 偏差分析
            add(DATA.ITTO.EARNED_VALUE_MANAGEMENT);                         // 挣值管理
            add(DATA.ITTO.FORECASTING);                                     // 预测
            add(DATA.ITTO.TO_COMPLETE_PERFORMANCE_INDEX);                   // 完工尚需绩效指数
            add(DATA.ITTO.APPROVED_CHANGE_REQUESTS_REVIEW);                 // 审计已批准的变更请求
            add(DATA.ITTO.RISK_AUDITS);                                     // 风险审计
            add(DATA.ITTO.RISK_REASSESSMENT);                               // 风险再评估
            add(DATA.ITTO.TECHNICAL_PERFORMANCE_MEASUREMENT);               // 技术绩效测量
            add(DATA.ITTO.VARIANCE_AND_TREND_ANALYSIS);                     // 偏差与趋势分析
            add(DATA.ITTO.CLAIM_ADMINISTRATION);                            // 索赔管理
            add(DATA.ITTO.CONTRACT_CHANGE_CONTROL_SYSTEM);                  // 合同变更控制系统
            add(DATA.ITTO.INSPECTIONS_AND_AUDITS);                          // 检查与审计
            add(DATA.ITTO.PAYMENT_SYSTEM);                                  // 支付系统
            add(DATA.ITTO.PROCUREMENT_PERFORMANCE_REVIEWS);                 // 采购绩效审查
            add(DATA.ITTO.CHANGE_CONTROL_TOOLS);                            // 变更控制工具
            add(DATA.ITTO.PROCUREMENT_AUDITS);                              // 采购审计
        }
    };
}
